image: docker:19.03.1
services:
  - docker:19.03.1-dind

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/backend:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-service:
  stage: build
  script:
    - docker build --no-cache -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE

