version: '3.8'

services:

  web:
    build: ./
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./:/usr/src
    env_file:
      - .env

  postgis:
    image: kartoza/postgis
    volumes:
      - nifa-postgis-data:/var/lib/postgresql
      - nifa-dbbackups:/backups
    ports:
      - 35432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
    env_file:
      - .env
