"""create_noaa_stations_table

Revision ID: 88f5448ba9d8
Revises:
Create Date: 2022-03-16 13:36:19.540638

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


# revision identifiers, used by Alembic.
revision = '88f5448ba9d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noaastationss',
    sa.Column('grid_id', sa.String(length=25), nullable=False),
    sa.Column('forecast_office_url', sa.String(length=255), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('forecast_url', sa.String(length=255), nullable=False),
    sa.Column('forecast_hourly_url', sa.String(length=255), nullable=False),
    sa.Column('forecast_grid_data_url', sa.String(length=255), nullable=False),
    sa.Column('observation_stations_url', sa.String(length=255), nullable=False),
    sa.Column('geometry', ga.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromGeoJSON', name='geometry', nullable=False)),
    sa.PrimaryKeyConstraint('grid_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noaastationss')
    # ### end Alembic commands ###
