"""add_collected_at_field_hourlyforecasts

Revision ID: 9375d66131ad
Revises: ae8c43c8470f
Create Date: 2022-03-21 15:42:51.470292

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


# revision identifiers, used by Alembic.
revision = '9375d66131ad'
down_revision = 'ae8c43c8470f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hourlyforecasts', sa.Column('collected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hourlyforecasts', 'collected_at')
    # ### end Alembic commands ###
