"""create_hourly_forecast_table

Revision ID: ae8c43c8470f
Revises: de40b6695d52
Create Date: 2022-03-21 14:45:54.051969

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


# revision identifiers, used by Alembic.
revision = "ae8c43c8470f"
down_revision = "de40b6695d52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hourlyforecasts",
        sa.Column("id", sa.String(length=255), primary_key=True),
        sa.Column("station", sa.String(length=25), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("wind_direction", sa.Integer(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station"],
            ["noaa_stations.grid_id"],
            name="fk_hourlyforecasts_noaa_stations_station_station",
        ),
        sa.UniqueConstraint(
            "station", "timestamp", name="uniq_hourlyforecasts_station_timestamp"
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hourlyforecasts")
    # ### end Alembic commands ###
